---
name: Debian Package

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'
  release:
    types:
      - created
  workflow_dispatch:
    inputs:
      si_input_semver_tag:
        description: Semantic Version (Optional for Rollback)
        required: false

jobs:
  configure:
    name: Configure Environment
    runs-on: ubuntu-latest
    outputs:
      si_config: ${{ steps.configure.outputs.si_config }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Shared Actions
        uses: ./.github/workflows/composites/shared-actions
        with:
          node-token: ${{ secrets.GH_NPM_READ_TOKEN }}
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Configure
        id: configure
        uses: ./.github/actions/composites/configure
        with:
          env-name: ${{ github.event.inputs.si_input_env_name }}
          semver: ${{ github.event.inputs.si_input_semver_tag }}

  package:
    name: Package Debian
    runs-on: ubuntu-20.04
    needs:
      - configure
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Shared Actions
        uses: ./.github/workflows/composites/shared-actions
        with:
          config: ${{ toJSON(needs.configure.outputs.si_config) }}
          node-token: ${{ secrets.GH_NPM_READ_TOKEN }}
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Package
        id: package
        uses: ./.github/actions/composites/deb-package
        with:
          environment: ${{ needs.configure.outputs.si_config }}

      - name: Validate
        uses: ./.github/actions/composites/deb-validate-install
        with:
          environment: ${{ needs.configure.outputs.si_config }}
          package-filepath: '${{ steps.package.outputs.si_deb_artifacts_directory }}/${{ steps.package.outputs.si_deb_package_filename }}'
          package-name: ${{ steps.package.outputs.si_deb_package }}

      - name: Archive
        uses: ./.github/actions/composites/deb-archive-artifact
        with:
          environment: ${{ needs.configure.outputs.si_config }}
          artifacts-directory: ${{ steps.package.outputs.si_deb_artifacts_directory }}
