---
name: Repository Setup

description: Runs initial commit for the repository template

inputs:
  github-email:
    description: GitHub email
    required: true
  github-user:
    description: GitHub user
    required: true
  node-token:
    description: Token for @simplesensio registry
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        git config --global user.email "${{ inputs.github-email }}"
        git config --global user.name "${{ inputs.github-user }}"

    - shell: bash
      run: |
        git checkout -b dev
        git push origin dev
        git checkout main

    - if: ${{ 'true' == github.event.inputs.github_pages }}
      shell: bash
      run: |
        git checkout -b gh-pages
        git push origin gh-pages
        git checkout main

    - env:
        NODE_AUTH_TOKEN: ${{ inputs.node-token }}
      shell: bash
      run: npm install -g npm-check-updates

    - id: metadata
      shell: bash
      run: node "${GITHUB_ACTION_PATH}/repo-metadata-setup.js" '${{ toJSON(github.event) }}'

    - env:
        SI_PRIVATE_REPO: ${{ steps.metadata.outputs.private }}
      shell: bash
      run: node "${GITHUB_ACTION_PATH}/repo-name-setup.js" '${{ toJSON(github.event) }}'

    - shell: bash
      run: node "${GITHUB_ACTION_PATH}/codeowners-setup.js" '${{ toJSON(github.event) }}'

    - env:
        SI_PRIVATE_REPO: ${{ steps.metadata.outputs.private }}
      shell: bash
      run: node "${GITHUB_ACTION_PATH}/npm-setup.js" '${{ toJSON(github.event) }}'

    - shell: bash
      run: node "${GITHUB_ACTION_PATH}/workflow-setup.js" '${{ toJSON(github.event) }}'

    - env:
        SI_WORKFLOW_LIST: pull-request.yaml rebase-main.yaml repository-settings.yaml schedule.yaml
      shell: bash
      run: |
        for FILENAME in $SI_WORKFLOW_LIST; do
          git mv "${{ github.workspace }}/.github/workflows/available/${FILENAME}" "${{ github.workspace }}/.github/workflows/${FILENAME}"
        done

    - if: ${{ null != github.event.inputs.ansible_roles }}
      env:
        SI_ANSIBLE_ROLES: ${{ github.event.inputs.ansible_roles }}
        SI_DESCRIPTION: ${{ github.event.inputs.description }}
      shell: bash
      run: sh "${GITHUB_ACTION_PATH}/ansible.sh"

    - if: ${{ 'CloudFormation' == github.event.inputs.artifact }}
      shell: bash
      run: git mv "${{ github.workspace }}/.github/workflows/available/deploy-cloudformation.yaml" "${{ github.workspace }}/.github/workflows/deploy-cloudformation.yaml"

    - if: ${{ 'Debian' == github.event.inputs.artifact }}
      shell: bash
      run: git mv "${{ github.workspace }}/.github/workflows/available/deploy-debian.yaml" "${{ github.workspace }}/.github/workflows/deploy-debian.yaml"

    - if: ${{ 'NPM' == github.event.inputs.artifact }}
      shell: bash
      run: git mv "${{ github.workspace }}/.github/workflows/available/deploy-npm.yaml" "${{ github.workspace }}/.github/workflows/deploy-npm.yaml"

    - if: ${{ 'true' == github.event.inputs.github_pages }}
      shell: bash
      run: git mv "${{ github.workspace }}/.github/workflows/available/deploy-github-pages.yaml" "${{ github.workspace }}/.github/workflows/deploy-github-pages.yaml"

    - if: ${{ 'Jest' == github.event.inputs.unit_test }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.node-token }}
      shell: bash
      run: |
        git mv "${{ github.workspace }}/.github/workflows/available/test-coverage-jest.yaml" "${{ github.workspace }}/.github/workflows/test-coverage-jest.yaml"
        git mv "${GITHUB_ACTION_PATH}/unit-test/jest" "${{ github.workspace }}/test"
        npm install jest --prefix "${{ github.workspace }}" --save-dev

    - env:
        SI_PRIVATE_REPO: ${{ steps.metadata.outputs.private }}
      shell: bash
      run: |
        case "${{ github.event.inputs.license }}" in
          IROC)
            git mv "${GITHUB_ACTION_PATH}/license/gov-iroc.md" "${{ github.workspace }}/LICENSE"
            ;;

          SSM)
            git mv "${GITHUB_ACTION_PATH}/license/gov-ssm.md" "${{ github.workspace }}/LICENSE"
            ;;

          *)
            if [[ "false" == "${SI_PRIVATE_REPO}" ]]; then
              git mv "${GITHUB_ACTION_PATH}/license/apache-2.0.md" "${{ github.workspace }}/LICENSE"
            else
              git mv "${GITHUB_ACTION_PATH}/license/default.md" "${{ github.workspace }}/LICENSE"
            fi
            ;;
        esac
        SI_FULL_YEAR=$(date +%Y)
        sed -i "s/SI_COPYRIGHT_YEAR/${SI_FULL_YEAR}/g" "${{ github.workspace }}/LICENSE"

    - shell: bash
      run: |
        rm -rf "${GITHUB_WORKSPACE}/.github/workflows/repository-setup.yaml" \
          "${GITHUB_WORKSPACE}/.github/workflows/composites/repository-setup/" \
          "${GITHUB_WORKSPACE}/.github/workflows/available/" \
          "${GITHUB_WORKSPACE}/.github/actions/"

    - env:
        NODE_AUTH_TOKEN: ${{ inputs.node-token }}
      shell: bash
      run: |
        ncu -u
        npm install

    - shell: bash
      run: npm run lint

    - shell: bash
      run: |
        git add -A
        git commit -m 'chore: repository setup'
        git push origin main
