---
name: GitHub Repository Setup

on:
  workflow_dispatch:
    inputs:
      artifact:
        description: Artifact Type
        required: false
        type: choice
        options:
          - None
          - CloudFormation
          - Debian
          - NPM
        default: None
      description:
        description: Repository Description
        required: true
      ansible_roles:
        description: CSV of Ansible roles to generate
        required: false
      github_pages:
        description: GitHub Pages?
        required: false
        type: boolean
        default: false
      license:
        description: Software License Type
        required: false
        type: choice
        options:
          - Default
          - IROC
          - SSM
        default: Default
      organization_team:
        description: Organization Team
        required: true
        type: choice
        options:
          - IROC
          - Prototype
          - Tendon
          - Tools
      unit_test:
        description: Unit Test Framework
        required: false
        type: choice
        options:
          - None
          - Jest
        default: None

jobs:
  setup:
    if: ${{ github.repository != 'simplesenseio/test-repo-template' }}
    name: Repository Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Shared Actions
        uses: ./.github/workflows/composites/shared-actions
        with:
          node-token: ${{ secrets.GH_NPM_READ_TOKEN }}
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Repository Setup Routine
        uses: ./.github/workflows/composites/repository-setup
        env:
          SI_GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          github-email: ${{ secrets.GH_USER_EMAIL }}
          github-user: ${{ secrets.GH_USER_NAME }}
          node-token: ${{ secrets.GH_NPM_READ_TOKEN }}
